trigger:
- main

variables:
  azureServiceConnectionId: 'myServiceConnection'
  webAppName: 'mywebapp248927'
  vmImageName: 'ubuntu-latest'
  environmentName: 'mydevopsvm'
  projectRoot: $(System.DefaultWorkingDirectory)
  pythonVersion: '3.9'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: |
        python -m venv antenv
        source antenv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      workingDirectory: $(projectRoot)
      displayName: "Install requirements"

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: $(projectRoot)
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  displayName: 'Deploy Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    environment: $(environmentName)
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop

          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App'
            inputs:
              azureSubscription: $(azureServiceConnectionId)
              appName: $(webAppName)
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'

          - script: |
              sudo apt-get update
              sudo apt-get install -y python3-pip
              sudo apt-get install -y chromium-browser
              python3 -m pip install selenium
              LATEST=$(wget -q -O - http://chromedriver.storage.googleapis.com/LATEST_RELEASE)
              wget http://chromedriver.storage.googleapis.com/$LATEST/chromedriver_linux64.zip
              unzip chromedriver_linux64.zip -d /usr/local/bin/
              sudo chmod +x /usr/local/bin/chromedriver
            displayName: 'Setup Environment for Functional Tests'

          - script: |
              pip3 install -r requirements.txt
              python3 -m unittest discover -s tests
            displayName: 'Run Functional Tests'
