trigger:
- main

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureServiceConnectionId: 'myServiceConnection'

  # Web app name
  webAppName: 'mywebapp248927'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # Environment name
  environmentName: 'devopsEnv2'

  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)

  # Python version: 3.9
  pythonVersion: '3.9'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool: myAgentPool
    steps:
    - script: |
        python -m venv mypy3env
        source mypy3env/bin/activate
        python -m pip install --upgrade pip
        pip install setup
        pip install -r requirements.txt
      workingDirectory: $(projectRoot)
      displayName: "Install requirements"

    - script: |
        export PATH=$HOME/.local/bin:$PATH
        make install        
      workingDirectory: $(projectRoot)
      displayName: 'install path requirements'

    - task: CmdLine@2
      continueOnError: true
      displayName: "Run commands"
      inputs:
        script: 'curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash'
      
    - task: CmdLine@2
      continueOnError: true
      displayName: "Run webapp"
      inputs:
        # script: 'az webapp up --sku B1 -n mywebapp248927 --resource-group azuredevops'
        script: 'python3 -m app run'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(projectRoot)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      displayName: 'Upload package'
      artifact: drop

- stage: Deploy
  displayName: 'Deploy Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    pool: myAgentPool
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App : mywebapp248927'
            inputs:
              azureSubscription: $(azureServiceConnectionId)
              appName: 'mywebapp248927'
              #appName: $(webAppName)
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
